name: Send Timesheet

on:
  schedule:
    # - cron: "* * * * *" # every minute
  workflow_dispatch: # manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MANAGER_EMAIL: ${{ secrets.MANAGER_EMAIL }}
          EMPLOYEE_NAME: ${{ secrets.EMPLOYEE_NAME }}
